# Generated by Django 5.1.3 on 2025-09-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicias_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
