# Generated by Django 5.1.3 on 2025-09-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicias_cafe', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
